import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import TopBar from "../components/LayoutComponents/TopBar";
import Sidebar from "../components/LayoutComponents/Sidebar";
import ReduxProvider from "../providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body>
        <main>
          <ReduxProvider>
            <TopBar />
            <div className="flex flex-wrap">
              <Sidebar />
              <main className="max-w-4/5 flex w-4/5 flex-wrap">{children}</main>
            </div>
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
